version: 2.1
orbs:
  slack: circleci/slack@3.4.2
jobs:
  build:
    docker:
      - image: circleci/node:10.21.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npx lerna bootstrap
      - run:
          name: Build
          command: npx lerna run build
      - run:
          name: Test
          command: npx lerna run test:ci
      - store_test_results:
          path: ./test-results
      - store_artifacts:
          path: ./test-results
      - persist_to_workspace:
          root: .
          paths:
            - packages
      - slack/status:
          channel: 'ci-cd'
          failure_message: 'Branch: ${CIRCLE_BRANCH}'
          success_message: 'Branch: ${CIRCLE_BRANCH}'
          mentions: 'U016N49F0CW,U017JM3DXUG'
          webhook: 'https://hooks.slack.com/services/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'
workflows:
  build:
    jobs:
      - build
