version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.21.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npx lerna bootstrap
      - run:
          name: Build
          command: npx lerna run build
      - run:
          name: Test
          command: npx lerna run test:ci
      - store_test_results:
          path: ./test-results
      - store_artifacts:
          path: ./test-results
      - persist_to_workspace:
          root: .
          paths:
            - packages
workflows:
  build:
    jobs:
      - build
